[package]
name = "bbase"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.33", features = ["serde"] }
graphql_client = { version = "0.13.0", features = ["reqwest", "reqwest-blocking"] }
reqwest = "0.11.24"
serde = { version = "1.0.196", features = ["derive"] }
